# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Example
on:
  push:
    branches: [ Dev]
  pull_request:
    branches: [ Dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
     - uses: actions/checkout@v2 
     - name: Run ansible playbook
       run: |
        sh ./script1.sh 

